from pathlib import Path

import click
import polars as pl
import altair as alt

from .config import Config
from . import output
from . import process
from . import plotting


DEFAULT_CONFIG_PATH = Path("config.toml")
ASCII_ART = """\
 ___ _
|  _| |_ _ _ _ ___ ___ ___
|  _| | | |_'_| . |  _| . |
|_| |_|___|_,_|  _|_| |___|
              |_|
"""


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
def cli():
    click.secho(ASCII_ART, bold=True, fg="green")


@cli.command()
def generate():
    """Generate an example config file"""
    with open(DEFAULT_CONFIG_PATH, "w") as f:
        f.write(Config.generate_example_toml())

    click.echo(
        f"Example config file written to {DEFAULT_CONFIG_PATH}",
        err=True,
    )


@cli.command()
@click.argument(
    "input_file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
)
@click.option(
    "-c",
    "--config",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=DEFAULT_CONFIG_PATH,
    show_default=True,
    help="Path to the config file",
)
def run(input_file: Path, config: Path):
    """Process the given file"""
    cfg = Config.from_toml(config)
    df = process.process_file(input_file, cfg)
    output_files = output.write_output(input_file, df)

    click.echo("Output files:", err=True)
    for file in output_files:
        click.echo("  " + file.as_posix(), err=True)


@cli.command()
@click.argument(
    "output_file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
)
def plot(output_file: Path):
    """Plot the results generated by fluxpro"""
    df = pl.read_csv(output_file, try_parse_dates=False)
    chart = plotting.plot_df(df)
    alt.renderers.enable("browser")
    chart.show()
